spring:
  application:
    name: asinfo-test-practice
  datasource:
    url: jdbc:postgresql://172.15.1.112:5432/test-practice
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:db.changelog.xml
    contexts: ${spring.profiles.active}
jwt:
  security: secret
  expiration: 43200
---
